"""Channel-adapter scaffold generator (T10a).

``predacore channel scaffold <name>`` writes a fully-typed starter
adapter into ``~/.predacore/channels/<name>.py`` so users can add
new channels without copy-pasting from existing ones.

The scaffold:
  * inherits from :class:`predacore.gateway.ChannelAdapter`
  * implements ``start`` / ``stop`` / ``send`` with TODO comments
  * shows the token-from-env pattern (used by every shipped adapter)
  * includes a streaming-buffer factory hook (T9 pattern, copy-paste ready)
  * adds a docstring listing the next steps (config edit, channel_install,
    secret_set)

Generation is plain string templating — no Jinja, no extra deps. The
output runs as-is the moment the user fills in the three TODO blocks
(API connect, on_message wiring, send call).
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# ``channel_name`` is matched against ``config.channels.enabled``, so we
# enforce the same allowed-character set the registry uses (lower snake).
_VALID_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _class_name(channel_name: str) -> str:
    """``matrix`` -> ``MatrixAdapter``; ``ms_teams`` -> ``MsTeamsAdapter``."""
    parts = channel_name.split("_")
    return "".join(p.capitalize() for p in parts) + "Adapter"


def _env_var_name(channel_name: str) -> str:
    """``matrix`` -> ``MATRIX_TOKEN`` (followed by the existing _SECRET_MAP convention)."""
    return f"{channel_name.upper()}_TOKEN"


_SCAFFOLD_TEMPLATE = '''"""
{channel_human} Channel Adapter — generated by ``predacore channel scaffold``.

Three things to do before this works:

  1. **Install the SDK** for {channel_human} (uncomment the import below).
  2. **Set the token** with the secret_set tool, or:
       export {env_var}=...
       (or write it into ~/.predacore/.env)
  3. **Enable the channel** in config:
       predacore-channel-add {channel_name}
     OR add ``{channel_name}`` to channels.enabled in ~/.predacore/config.yaml.

After that, the daemon's config-watcher hot-attaches the adapter (PR T8) —
no restart needed.

Implement the THREE TODO blocks below. Everything else (rate limiting,
streaming, health monitoring, hot-attach) is provided by the framework.
"""
from __future__ import annotations

import asyncio
import logging
import os

# TODO 1/3 — import the platform's SDK. Examples:
#   import nio                            # Matrix
#   from mattermostdriver import Driver   # Mattermost
#   from atproto import Client            # Bluesky
#   from mastodon import Mastodon         # Mastodon

from predacore.config import PredaCoreConfig
from predacore.gateway import ChannelAdapter, IncomingMessage, OutgoingMessage
from predacore.channels.streaming import StreamingMessageBuffer

logger = logging.getLogger(__name__)


class {class_name}(ChannelAdapter):
    """Adapter for {channel_human}."""

    channel_name = "{channel_name}"
    # Capabilities follow the convention used by every shipped adapter
    # (see telegram.py, slack.py, etc.). Adjust per the platform.
    channel_capabilities = {{
        "supports_media": False,
        "supports_buttons": False,
        "supports_embeds": False,
        "supports_markdown": True,
        "max_message_length": 4096,
    }}

    def __init__(self, config: PredaCoreConfig):
        super().__init__()
        self.config = config
        # Token resolution mirrors every shipped adapter:
        #   1) channel-specific config block in config.yaml
        #   2) environment variable {env_var}
        #   3) ~/.predacore/.env (autoloaded by the daemon)
        ch_cfg = getattr(config.channels, "{channel_name}", None) or {{}}
        self._token = (
            (ch_cfg.get("token") if isinstance(ch_cfg, dict) else None)
            or os.environ.get("{env_var}", "")
        )
        if not self._token:
            logger.warning(
                "{channel_human}: no token configured — set {env_var} or "
                "channels.{channel_name}.token in config.yaml",
            )
        self._client = None
        self._running = False

    # ── Lifecycle ─────────────────────────────────────────────────────

    async def start(self) -> None:
        """Connect + register the on_message callback.

        TODO 2/3 — replace this with the platform's connect+listen call.
        Most SDKs expose either:
          - a long-poll loop you await in a background task, or
          - an event-driven client where you bind ``on_message`` callbacks.

        Whichever pattern, when an incoming message arrives:
          1. extract the user_id (platform-specific id) and text
          2. await ``self._on_incoming(user_id, text, metadata=...)``
          3. that wrapper drives the gateway + sends the response back
        """
        if not self._token:
            logger.error("{channel_human}: refusing to start — no token")
            return
        # Example (matrix-nio style):
        #     self._client = nio.AsyncClient(homeserver_url, user_id)
        #     await self._client.login(self._token)
        #     self._client.add_event_callback(self._on_event, nio.RoomMessageText)
        #     self._sync_task = asyncio.create_task(self._client.sync_forever(timeout=30000))
        self._running = True
        logger.info("{channel_human} adapter started (placeholder)")

    async def stop(self) -> None:
        """Disconnect cleanly. Called by the gateway on daemon shutdown."""
        self._running = False
        if self._client is not None:
            # await self._client.close()
            self._client = None
        logger.info("{channel_human} adapter stopped")

    # ── Outgoing ──────────────────────────────────────────────────────

    async def send(self, message: OutgoingMessage) -> None:
        """Send a response to the platform.

        TODO 3/3 — call the platform's send method here.
        ``message.user_id`` is whatever you passed in via IncomingMessage
        when you forwarded the user's message — typically the platform's
        chat/conversation id.
        """
        if self._client is None:
            logger.error("{channel_human}: not connected, dropping outgoing")
            return
        # Example:
        #     await self._client.room_send(
        #         room_id=message.user_id,
        #         message_type="m.room.message",
        #         content={{"msgtype": "m.text", "body": message.text}},
        #     )
        logger.info("{channel_human} send: %s", message.text[:80])

    # ── Incoming wiring ───────────────────────────────────────────────

    async def _on_incoming(
        self,
        user_id: str,
        text: str,
        *,
        metadata: dict | None = None,
    ) -> None:
        """Forward an incoming user message to the gateway, stream the
        reply back, and fall back to a non-streamed send if streaming
        couldn't start (e.g. platform rate-limit on the placeholder).
        """
        if not self._message_handler:
            return

        # Streaming buffer — see predacore/channels/streaming.py for the
        # contract. Adjust ``edit_min_interval_seconds`` per the platform's
        # edit rate limit (~1.0s is the common Goldilocks value).
        buffer = self._make_stream_buffer(target=user_id)

        outgoing = await self._message_handler(
            IncomingMessage(
                channel=self.channel_name,
                user_id=user_id,
                text=text,
                metadata=metadata or {{}},
            ),
            stream_fn=buffer.feed,
        )
        if outgoing is None:
            return
        handle = await buffer.flush(outgoing.text)
        if handle is None:
            await self.send(outgoing)

    def _make_stream_buffer(self, *, target: str) -> StreamingMessageBuffer:
        """Per-message streaming buffer. The two callbacks below are the
        only platform-specific hooks streaming needs."""
        async def _send_initial(text: str):
            # TODO — return the platform's message id so we can edit it later.
            # If the platform doesn't support edits, return None and the
            # buffer will gracefully degrade to non-streaming.
            return None

        async def _edit(handle, text: str):
            # TODO — edit the message at ``handle`` to ``text``.
            return

        return StreamingMessageBuffer(
            send_initial=_send_initial,
            edit=_edit,
            edit_min_interval_seconds=1.0,
            max_chars=3500,
        )
'''


def generate_scaffold(
    channel_name: str,
    plugin_dir: str | Path | None = None,
    *,
    overwrite: bool = False,
) -> Path:
    """Write a starter adapter into ``plugin_dir`` for ``channel_name``.

    Returns the path of the newly-created file. Raises ``ValueError`` for
    invalid names; raises ``FileExistsError`` when the target already
    exists and ``overwrite=False``.
    """
    if not _VALID_NAME_RE.match(channel_name):
        raise ValueError(
            f"channel_name {channel_name!r} must match {_VALID_NAME_RE.pattern} "
            "(lowercase, snake_case, starts with a letter)"
        )

    if plugin_dir is None:
        plugin_dir = Path.home() / ".predacore" / "channels"
    plugin_dir = Path(plugin_dir).expanduser()
    plugin_dir.mkdir(parents=True, exist_ok=True)

    target = plugin_dir / f"{channel_name}.py"
    if target.exists() and not overwrite:
        raise FileExistsError(
            f"{target} already exists — pass overwrite=True to replace it"
        )

    body = _SCAFFOLD_TEMPLATE.format(
        channel_name=channel_name,
        channel_human=channel_name.replace("_", " ").title(),
        class_name=_class_name(channel_name),
        env_var=_env_var_name(channel_name),
    )
    target.write_text(body)
    logger.info("Wrote channel scaffold: %s", target)
    return target
