# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import csc_pb2 as csc__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in csc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CentralStrategicCoreServiceStub:
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessGoal = channel.unary_unary(
                '/project_prometheus.common.protos.CentralStrategicCoreService/ProcessGoal',
                request_serializer=csc__pb2.ProcessGoalRequest.SerializeToString,
                response_deserializer=csc__pb2.ProcessGoalResponse.FromString,
                _registered_method=True)
        self.GetGoalStatus = channel.unary_unary(
                '/project_prometheus.common.protos.CentralStrategicCoreService/GetGoalStatus',
                request_serializer=csc__pb2.GetGoalStatusRequest.SerializeToString,
                response_deserializer=csc__pb2.GetGoalStatusResponse.FromString,
                _registered_method=True)
        self.GetPlanDetails = channel.unary_unary(
                '/project_prometheus.common.protos.CentralStrategicCoreService/GetPlanDetails',
                request_serializer=csc__pb2.GetPlanDetailsRequest.SerializeToString,
                response_deserializer=csc__pb2.PlanMessage.FromString,
                _registered_method=True)


class CentralStrategicCoreServiceServicer:
    """--- Service Definition ---

    """

    def ProcessGoal(self, request, context):
        """Main entry point for user goals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoalStatus(self, request, context):
        """Status monitoring methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlanDetails(self, request, context):
        """Returns plan or error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralStrategicCoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessGoal,
                    request_deserializer=csc__pb2.ProcessGoalRequest.FromString,
                    response_serializer=csc__pb2.ProcessGoalResponse.SerializeToString,
            ),
            'GetGoalStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoalStatus,
                    request_deserializer=csc__pb2.GetGoalStatusRequest.FromString,
                    response_serializer=csc__pb2.GetGoalStatusResponse.SerializeToString,
            ),
            'GetPlanDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlanDetails,
                    request_deserializer=csc__pb2.GetPlanDetailsRequest.FromString,
                    response_serializer=csc__pb2.PlanMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project_prometheus.common.protos.CentralStrategicCoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project_prometheus.common.protos.CentralStrategicCoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentralStrategicCoreService:
    """--- Service Definition ---

    """

    @staticmethod
    def ProcessGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.CentralStrategicCoreService/ProcessGoal',
            csc__pb2.ProcessGoalRequest.SerializeToString,
            csc__pb2.ProcessGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGoalStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.CentralStrategicCoreService/GetGoalStatus',
            csc__pb2.GetGoalStatusRequest.SerializeToString,
            csc__pb2.GetGoalStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlanDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.CentralStrategicCoreService/GetPlanDetails',
            csc__pb2.GetPlanDetailsRequest.SerializeToString,
            csc__pb2.PlanMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
