# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import egm_pb2 as egm__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in egm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EthicalGovernanceModuleServiceStub:
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckPlanCompliance = channel.unary_unary(
                '/project_prometheus.common.protos.EthicalGovernanceModuleService/CheckPlanCompliance',
                request_serializer=egm__pb2.CheckPlanComplianceRequest.SerializeToString,
                response_deserializer=egm__pb2.ComplianceCheckResultMessage.FromString,
                _registered_method=True)
        self.CheckActionCompliance = channel.unary_unary(
                '/project_prometheus.common.protos.EthicalGovernanceModuleService/CheckActionCompliance',
                request_serializer=egm__pb2.CheckActionComplianceRequest.SerializeToString,
                response_deserializer=egm__pb2.ComplianceCheckResultMessage.FromString,
                _registered_method=True)
        self.LogEvent = channel.unary_unary(
                '/project_prometheus.common.protos.EthicalGovernanceModuleService/LogEvent',
                request_serializer=egm__pb2.LogEventRequest.SerializeToString,
                response_deserializer=egm__pb2.LogEventResponse.FromString,
                _registered_method=True)
        self.SanitizeInput = channel.unary_unary(
                '/project_prometheus.common.protos.EthicalGovernanceModuleService/SanitizeInput',
                request_serializer=egm__pb2.SanitizeInputRequest.SerializeToString,
                response_deserializer=egm__pb2.SanitizeInputResponse.FromString,
                _registered_method=True)
        self.SanitizeOutput = channel.unary_unary(
                '/project_prometheus.common.protos.EthicalGovernanceModuleService/SanitizeOutput',
                request_serializer=egm__pb2.SanitizeOutputRequest.SerializeToString,
                response_deserializer=egm__pb2.SanitizeOutputResponse.FromString,
                _registered_method=True)


class EthicalGovernanceModuleServiceServicer:
    """--- Service Definition ---

    """

    def CheckPlanCompliance(self, request, context):
        """Compliance Checking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckActionCompliance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogEvent(self, request, context):
        """Auditing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SanitizeInput(self, request, context):
        """Utility Functions (May move to a separate utility service later)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SanitizeOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EthicalGovernanceModuleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckPlanCompliance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPlanCompliance,
                    request_deserializer=egm__pb2.CheckPlanComplianceRequest.FromString,
                    response_serializer=egm__pb2.ComplianceCheckResultMessage.SerializeToString,
            ),
            'CheckActionCompliance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckActionCompliance,
                    request_deserializer=egm__pb2.CheckActionComplianceRequest.FromString,
                    response_serializer=egm__pb2.ComplianceCheckResultMessage.SerializeToString,
            ),
            'LogEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEvent,
                    request_deserializer=egm__pb2.LogEventRequest.FromString,
                    response_serializer=egm__pb2.LogEventResponse.SerializeToString,
            ),
            'SanitizeInput': grpc.unary_unary_rpc_method_handler(
                    servicer.SanitizeInput,
                    request_deserializer=egm__pb2.SanitizeInputRequest.FromString,
                    response_serializer=egm__pb2.SanitizeInputResponse.SerializeToString,
            ),
            'SanitizeOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SanitizeOutput,
                    request_deserializer=egm__pb2.SanitizeOutputRequest.FromString,
                    response_serializer=egm__pb2.SanitizeOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project_prometheus.common.protos.EthicalGovernanceModuleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project_prometheus.common.protos.EthicalGovernanceModuleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EthicalGovernanceModuleService:
    """--- Service Definition ---

    """

    @staticmethod
    def CheckPlanCompliance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.EthicalGovernanceModuleService/CheckPlanCompliance',
            egm__pb2.CheckPlanComplianceRequest.SerializeToString,
            egm__pb2.ComplianceCheckResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckActionCompliance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.EthicalGovernanceModuleService/CheckActionCompliance',
            egm__pb2.CheckActionComplianceRequest.SerializeToString,
            egm__pb2.ComplianceCheckResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.EthicalGovernanceModuleService/LogEvent',
            egm__pb2.LogEventRequest.SerializeToString,
            egm__pb2.LogEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SanitizeInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.EthicalGovernanceModuleService/SanitizeInput',
            egm__pb2.SanitizeInputRequest.SerializeToString,
            egm__pb2.SanitizeInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SanitizeOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.EthicalGovernanceModuleService/SanitizeOutput',
            egm__pb2.SanitizeOutputRequest.SerializeToString,
            egm__pb2.SanitizeOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
