# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import wil_pb2 as wil__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wil_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorldInteractionLayerServiceStub(object):
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAvailableTools = channel.unary_unary(
                '/project_prometheus.common.protos.WorldInteractionLayerService/ListAvailableTools',
                request_serializer=wil__pb2.ListAvailableToolsRequest.SerializeToString,
                response_deserializer=wil__pb2.ListAvailableToolsResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/project_prometheus.common.protos.WorldInteractionLayerService/ExecuteTool',
                request_serializer=wil__pb2.InteractionRequestMessage.SerializeToString,
                response_deserializer=wil__pb2.InteractionResultMessage.FromString,
                _registered_method=True)
        self.ExecuteCode = channel.unary_unary(
                '/project_prometheus.common.protos.WorldInteractionLayerService/ExecuteCode',
                request_serializer=wil__pb2.CodeExecutionRequestMessage.SerializeToString,
                response_deserializer=wil__pb2.CodeExecutionResultMessage.FromString,
                _registered_method=True)


class WorldInteractionLayerServiceServicer(object):
    """--- Service Definition ---

    """

    def ListAvailableTools(self, request, context):
        """Get available tools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Execute general tools (API, Web Scraper)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCode(self, request, context):
        """Execute code specifically
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorldInteractionLayerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAvailableTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableTools,
                    request_deserializer=wil__pb2.ListAvailableToolsRequest.FromString,
                    response_serializer=wil__pb2.ListAvailableToolsResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=wil__pb2.InteractionRequestMessage.FromString,
                    response_serializer=wil__pb2.InteractionResultMessage.SerializeToString,
            ),
            'ExecuteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCode,
                    request_deserializer=wil__pb2.CodeExecutionRequestMessage.FromString,
                    response_serializer=wil__pb2.CodeExecutionResultMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project_prometheus.common.protos.WorldInteractionLayerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project_prometheus.common.protos.WorldInteractionLayerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorldInteractionLayerService(object):
    """--- Service Definition ---

    """

    @staticmethod
    def ListAvailableTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.WorldInteractionLayerService/ListAvailableTools',
            wil__pb2.ListAvailableToolsRequest.SerializeToString,
            wil__pb2.ListAvailableToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.WorldInteractionLayerService/ExecuteTool',
            wil__pb2.InteractionRequestMessage.SerializeToString,
            wil__pb2.InteractionResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.WorldInteractionLayerService/ExecuteCode',
            wil__pb2.CodeExecutionRequestMessage.SerializeToString,
            wil__pb2.CodeExecutionResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
