# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import daf_pb2 as daf__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DynamicAgentFabricControllerServiceStub(object):
    """DispatchTask uses TaskAssignmentMessage as request and TaskResultMessage as response

    --- Service Definition ---

    Name reflects future goal
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAgentTypes = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/ListAgentTypes',
                request_serializer=daf__pb2.ListAgentTypesRequest.SerializeToString,
                response_deserializer=daf__pb2.ListAgentTypesResponse.FromString,
                _registered_method=True)
        self.SpawnAgent = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/SpawnAgent',
                request_serializer=daf__pb2.SpawnAgentRequest.SerializeToString,
                response_deserializer=daf__pb2.SpawnAgentResponse.FromString,
                _registered_method=True)
        self.RetireAgent = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/RetireAgent',
                request_serializer=daf__pb2.RetireAgentRequest.SerializeToString,
                response_deserializer=daf__pb2.RetireAgentResponse.FromString,
                _registered_method=True)
        self.DispatchTask = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/DispatchTask',
                request_serializer=daf__pb2.TaskAssignmentMessage.SerializeToString,
                response_deserializer=daf__pb2.TaskResultMessage.FromString,
                _registered_method=True)
        self.RegisterAgentInstance = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/RegisterAgentInstance',
                request_serializer=daf__pb2.RegisterAgentInstanceRequest.SerializeToString,
                response_deserializer=daf__pb2.RegisterAgentInstanceResponse.FromString,
                _registered_method=True)
        self.AgentHeartbeat = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/AgentHeartbeat',
                request_serializer=daf__pb2.AgentHeartbeatMessage.SerializeToString,
                response_deserializer=daf__pb2.AgentHeartbeatResponse.FromString,
                _registered_method=True)
        self.GetNextTask = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/GetNextTask',
                request_serializer=daf__pb2.GetNextTaskRequest.SerializeToString,
                response_deserializer=daf__pb2.GetNextTaskResponse.FromString,
                _registered_method=True)
        self.ReportTaskResult = channel.unary_unary(
                '/project_prometheus.common.protos.DynamicAgentFabricControllerService/ReportTaskResult',
                request_serializer=daf__pb2.ReportTaskResultRequest.SerializeToString,
                response_deserializer=daf__pb2.ReportTaskResultResponse.FromString,
                _registered_method=True)


class DynamicAgentFabricControllerServiceServicer(object):
    """DispatchTask uses TaskAssignmentMessage as request and TaskResultMessage as response

    --- Service Definition ---

    Name reflects future goal
    """

    def ListAgentTypes(self, request, context):
        """List the predefined agent types available
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnAgent(self, request, context):
        """Spawn a new agent instance of a specific type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetireAgent(self, request, context):
        """Retire (terminate) a specific agent instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchTask(self, request, context):
        """Dispatch a task defined by CSC to the appropriate agent/tool handler
        Can target by capability, type, or specific instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgentInstance(self, request, context):
        """--- Agent Pull Loop RPCs (Phase 2) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DynamicAgentFabricControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAgentTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentTypes,
                    request_deserializer=daf__pb2.ListAgentTypesRequest.FromString,
                    response_serializer=daf__pb2.ListAgentTypesResponse.SerializeToString,
            ),
            'SpawnAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnAgent,
                    request_deserializer=daf__pb2.SpawnAgentRequest.FromString,
                    response_serializer=daf__pb2.SpawnAgentResponse.SerializeToString,
            ),
            'RetireAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RetireAgent,
                    request_deserializer=daf__pb2.RetireAgentRequest.FromString,
                    response_serializer=daf__pb2.RetireAgentResponse.SerializeToString,
            ),
            'DispatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchTask,
                    request_deserializer=daf__pb2.TaskAssignmentMessage.FromString,
                    response_serializer=daf__pb2.TaskResultMessage.SerializeToString,
            ),
            'RegisterAgentInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgentInstance,
                    request_deserializer=daf__pb2.RegisterAgentInstanceRequest.FromString,
                    response_serializer=daf__pb2.RegisterAgentInstanceResponse.SerializeToString,
            ),
            'AgentHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.AgentHeartbeat,
                    request_deserializer=daf__pb2.AgentHeartbeatMessage.FromString,
                    response_serializer=daf__pb2.AgentHeartbeatResponse.SerializeToString,
            ),
            'GetNextTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextTask,
                    request_deserializer=daf__pb2.GetNextTaskRequest.FromString,
                    response_serializer=daf__pb2.GetNextTaskResponse.SerializeToString,
            ),
            'ReportTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskResult,
                    request_deserializer=daf__pb2.ReportTaskResultRequest.FromString,
                    response_serializer=daf__pb2.ReportTaskResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project_prometheus.common.protos.DynamicAgentFabricControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project_prometheus.common.protos.DynamicAgentFabricControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DynamicAgentFabricControllerService(object):
    """DispatchTask uses TaskAssignmentMessage as request and TaskResultMessage as response

    --- Service Definition ---

    Name reflects future goal
    """

    @staticmethod
    def ListAgentTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/ListAgentTypes',
            daf__pb2.ListAgentTypesRequest.SerializeToString,
            daf__pb2.ListAgentTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpawnAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/SpawnAgent',
            daf__pb2.SpawnAgentRequest.SerializeToString,
            daf__pb2.SpawnAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetireAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/RetireAgent',
            daf__pb2.RetireAgentRequest.SerializeToString,
            daf__pb2.RetireAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/DispatchTask',
            daf__pb2.TaskAssignmentMessage.SerializeToString,
            daf__pb2.TaskResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgentInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/RegisterAgentInstance',
            daf__pb2.RegisterAgentInstanceRequest.SerializeToString,
            daf__pb2.RegisterAgentInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/AgentHeartbeat',
            daf__pb2.AgentHeartbeatMessage.SerializeToString,
            daf__pb2.AgentHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/GetNextTask',
            daf__pb2.GetNextTaskRequest.SerializeToString,
            daf__pb2.GetNextTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.DynamicAgentFabricControllerService/ReportTaskResult',
            daf__pb2.ReportTaskResultRequest.SerializeToString,
            daf__pb2.ReportTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
