# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import knowledge_nexus_pb2 as knowledge__nexus__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_nexus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeNexusServiceStub(object):
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryNodes = channel.unary_unary(
                '/project_prometheus.common.protos.KnowledgeNexusService/QueryNodes',
                request_serializer=knowledge__nexus__pb2.QueryNodesRequest.SerializeToString,
                response_deserializer=knowledge__nexus__pb2.QueryNodesResponse.FromString,
                _registered_method=True)
        self.QueryEdges = channel.unary_unary(
                '/project_prometheus.common.protos.KnowledgeNexusService/QueryEdges',
                request_serializer=knowledge__nexus__pb2.QueryEdgesRequest.SerializeToString,
                response_deserializer=knowledge__nexus__pb2.QueryEdgesResponse.FromString,
                _registered_method=True)
        self.GetNodeDetails = channel.unary_unary(
                '/project_prometheus.common.protos.KnowledgeNexusService/GetNodeDetails',
                request_serializer=knowledge__nexus__pb2.GetNodeDetailsRequest.SerializeToString,
                response_deserializer=knowledge__nexus__pb2.KnowledgeNodeMessage.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/project_prometheus.common.protos.KnowledgeNexusService/SemanticSearch',
                request_serializer=knowledge__nexus__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=knowledge__nexus__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.AddRelation = channel.unary_unary(
                '/project_prometheus.common.protos.KnowledgeNexusService/AddRelation',
                request_serializer=knowledge__nexus__pb2.AddRelationRequest.SerializeToString,
                response_deserializer=knowledge__nexus__pb2.KnowledgeEdgeMessage.FromString,
                _registered_method=True)
        self.IngestText = channel.unary_unary(
                '/project_prometheus.common.protos.KnowledgeNexusService/IngestText',
                request_serializer=knowledge__nexus__pb2.IngestTextRequest.SerializeToString,
                response_deserializer=knowledge__nexus__pb2.IngestTextResponse.FromString,
                _registered_method=True)


class KnowledgeNexusServiceServicer(object):
    """--- Service Definition ---

    """

    def QueryNodes(self, request, context):
        """Query Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeDetails(self, request, context):
        """Returns node or error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRelation(self, request, context):
        """Modification Methods
        Returns created edge or error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestText(self, request, context):
        """Ingestion Methods (Simplified for v1)
        rpc IngestStructuredData(...) returns (...); // Add later
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeNexusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryNodes,
                    request_deserializer=knowledge__nexus__pb2.QueryNodesRequest.FromString,
                    response_serializer=knowledge__nexus__pb2.QueryNodesResponse.SerializeToString,
            ),
            'QueryEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryEdges,
                    request_deserializer=knowledge__nexus__pb2.QueryEdgesRequest.FromString,
                    response_serializer=knowledge__nexus__pb2.QueryEdgesResponse.SerializeToString,
            ),
            'GetNodeDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeDetails,
                    request_deserializer=knowledge__nexus__pb2.GetNodeDetailsRequest.FromString,
                    response_serializer=knowledge__nexus__pb2.KnowledgeNodeMessage.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=knowledge__nexus__pb2.SemanticSearchRequest.FromString,
                    response_serializer=knowledge__nexus__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'AddRelation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRelation,
                    request_deserializer=knowledge__nexus__pb2.AddRelationRequest.FromString,
                    response_serializer=knowledge__nexus__pb2.KnowledgeEdgeMessage.SerializeToString,
            ),
            'IngestText': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestText,
                    request_deserializer=knowledge__nexus__pb2.IngestTextRequest.FromString,
                    response_serializer=knowledge__nexus__pb2.IngestTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project_prometheus.common.protos.KnowledgeNexusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project_prometheus.common.protos.KnowledgeNexusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeNexusService(object):
    """--- Service Definition ---

    """

    @staticmethod
    def QueryNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.KnowledgeNexusService/QueryNodes',
            knowledge__nexus__pb2.QueryNodesRequest.SerializeToString,
            knowledge__nexus__pb2.QueryNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.KnowledgeNexusService/QueryEdges',
            knowledge__nexus__pb2.QueryEdgesRequest.SerializeToString,
            knowledge__nexus__pb2.QueryEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.KnowledgeNexusService/GetNodeDetails',
            knowledge__nexus__pb2.GetNodeDetailsRequest.SerializeToString,
            knowledge__nexus__pb2.KnowledgeNodeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.KnowledgeNexusService/SemanticSearch',
            knowledge__nexus__pb2.SemanticSearchRequest.SerializeToString,
            knowledge__nexus__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRelation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.KnowledgeNexusService/AddRelation',
            knowledge__nexus__pb2.AddRelationRequest.SerializeToString,
            knowledge__nexus__pb2.KnowledgeEdgeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project_prometheus.common.protos.KnowledgeNexusService/IngestText',
            knowledge__nexus__pb2.IngestTextRequest.SerializeToString,
            knowledge__nexus__pb2.IngestTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
