"""
Common data models used across Project Prometheus components.
Leverages Pydantic for validation and type hints.
"""
from enum import Enum
from typing import Any, Optional, Union
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

# Placeholder for actual vector type - could be list[float], np.ndarray, etc.
# Using Any for now to avoid strict dependency on numpy if not always used.
VectorEmbedding = Any  # Or: TypeAlias = Union[List[float], np.ndarray]


class KnowledgeNode(BaseModel):
    """
    Represents an entity or concept node in the Knowledge Nexus.
    """

    id: UUID = Field(default_factory=uuid4)
    labels: set[str] = Field(
        default_factory=set,
        description="Set of labels defining the node type/category.",
    )
    properties: dict[str, Any] = Field(
        default_factory=dict, description="Key-value properties of the node."
    )
    embedding: VectorEmbedding | None = Field(
        None, description="Optional vector embedding for similarity search."
    )
    layers: set[str] = Field(
        default_factory=set,
        description="Set of layer identifiers this node belongs to.",
    )

    class Config:
        # Allow numpy arrays if used for embeddings (or other custom types)
        arbitrary_types_allowed = True


class KnowledgeEdge(BaseModel):
    """
    Represents a relationship (edge) between two KnowledgeNodes.
    """

    id: UUID = Field(default_factory=uuid4)
    source_node_id: UUID = Field(description="Identifier of the starting node.")
    target_node_id: UUID = Field(description="Identifier of the ending node.")
    type: str = Field(
        description="String defining the relationship type (e.g., 'HAS_CAPABILITY')."
    )
    properties: dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value properties of the edge (e.g., confidence, source).",
    )
    layers: set[str] = Field(
        default_factory=set,
        description="Set of layer identifiers this edge belongs to.",
    )


# --- CSC Related Models ---


class StatusEnum(str, Enum):
    """Enum for Goal/Plan/Step status, mirroring csc.proto."""

    UNSPECIFIED = "UNSPECIFIED"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    READY = "READY"
    EXECUTING = "EXECUTING"


class PlanStep(BaseModel):
    """
    Represents a single step within a Plan.
    """

    id: UUID = Field(default_factory=uuid4)
    description: str = Field(description="Human-readable description of the step.")
    action_type: str = Field(
        description="Type of action (e.g., QUERY_KN, INVOKE_TOOL)."
    )
    parameters: dict[str, Any] = Field(
        default_factory=dict, description="Parameters needed for the action."
    )
    required_knowledge_ids: list[UUID] = Field(
        default_factory=list, description="References to KN node IDs needed."
    )
    status: StatusEnum = Field(default=StatusEnum.PENDING)
    result: Any | None = Field(None, description="Outcome of the step execution.")


class Plan(BaseModel):
    """
    Represents a plan generated by the CSC to achieve a goal.
    """

    id: UUID = Field(default_factory=uuid4)
    goal_id: UUID = Field(description="The goal this plan addresses.")
    steps: list[PlanStep] = Field(
        default_factory=list, description="Ordered list of steps in the plan."
    )
    status: StatusEnum = Field(default=StatusEnum.PENDING)
    confidence: float | None = Field(
        None, description="Estimated likelihood of success."
    )
    justification: str | None = Field(None, description="High-level reasoning trace.")


# --- WIL Related Models ---


class ToolTypeEnum(str, Enum):
    """Enum for Tool types, mirroring wil.proto."""

    UNSPECIFIED = "UNSPECIFIED"
    API = "API"
    WEB_SCRAPER = "WEB_SCRAPER"
    CODE_EXECUTOR = "CODE_EXECUTOR"


class InteractionStatusEnum(str, Enum):
    """Enum for Interaction status, mirroring wil.proto."""

    UNSPECIFIED = "UNSPECIFIED"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    ERROR = "ERROR"
    TIMEOUT = "TIMEOUT"


class ToolDescription(BaseModel):
    """
    Internal representation of a tool available to the WIL.
    """

    tool_id: str = Field(description="Unique identifier for the tool.")
    tool_type: ToolTypeEnum
    description: str
    input_schema: dict[str, Any] = Field(
        default_factory=dict,
        description="Schema for input parameters (e.g., JSON schema).",
    )
    output_schema: dict[str, Any] = Field(
        default_factory=dict, description="Schema for output data."
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Other tool-specific info (e.g., base URL)."
    )


class InteractionRequest(BaseModel):
    """
    Represents a request to execute a tool via WIL.
    """

    request_id: UUID = Field(default_factory=uuid4)
    tool_id: str
    parameters: dict[str, Any] = Field(default_factory=dict)
    credentials: dict[str, Any] | None = None  # Store securely, maybe reference secrets
    context: dict[str, Any] | None = None


class InteractionResult(BaseModel):
    """
    Represents the result of a tool execution via WIL.
    """

    request_id: UUID
    status: InteractionStatusEnum
    output: Any | None = None  # Can be dict, list, str, number etc.
    error_message: str | None = None
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Execution details like duration."
    )


class CodeExecutionRequest(BaseModel):
    """
    Specific request for code execution.
    """

    request_id: UUID = Field(default_factory=uuid4)
    # tool_id is implicitly CODE_EXECUTOR
    code: str
    input_args: list[Any] | dict[str, Any] | None = None
    timeout_seconds: int = 60  # Default timeout
    context: dict[str, Any] | None = None


class CodeExecutionResult(BaseModel):
    """
    Specific result for code execution.
    """

    request_id: UUID
    status: InteractionStatusEnum
    stdout: str = ""
    stderr: str = ""
    result: Any | None = None  # Return value from code, if any
    error_message: str | None = None


# --- DAF Related Models ---


class AgentDescription(BaseModel):
    """
    Internal representation of a predefined agent type (DAF v0.5).
    """

    agent_type_id: str = Field(description="Unique identifier for the agent role.")
    description: str
    supported_actions: list[str] = Field(
        default_factory=list,
        description="High-level actions/capabilities this agent type can perform.",
    )
    required_tools: list[str] = Field(
        default_factory=list,
        description="WIL tool IDs typically used by this agent type.",
    )
    configuration: dict[str, Any] = Field(
        default_factory=dict, description="Static configuration for this agent type."
    )


class TaskAssignment(BaseModel):
    """
    Represents a task assigned by CSC to the DAF.
    """

    task_id: UUID = Field(default_factory=uuid4)
    plan_step_id: UUID = Field(
        description="The CSC plan step this task corresponds to."
    )
    required_capability: str | None = Field(
        None, description="General capability needed (e.g., 'search_web')."
    )
    agent_type_id: str | None = Field(
        None, description="Specific agent type requested."
    )
    parameters: dict[str, Any] = Field(
        default_factory=dict, description="Input data/parameters for the task."
    )
    context: dict[str, Any] | None = Field(
        None, description="Context like goal ID, user ID."
    )

    # Add validation later to ensure either required_capability or agent_type_id is provided


class TaskResult(BaseModel):
    """
    Represents the result of a task executed by DAF.
    """

    task_id: UUID
    plan_step_id: UUID
    status: InteractionStatusEnum  # Reuse WIL status enum
    output: Any | None = None  # Result data from agent/tool
    error_message: str | None = None
    agent_type_id_used: str | None = Field(
        None, description="Which agent type handled the task."
    )


# Example Usage (for illustration):

# Example Usage (for illustration):
if __name__ == "__main__":
    node1 = KnowledgeNode(labels={"Concept", "Software"}, properties={"name": "Python"})
    node2 = KnowledgeNode(
        labels={"Concept", "Library"},
        properties={"name": "Pydantic", "language": "Python"},
    )
    edge = KnowledgeEdge(
        source_node_id=node2.id,
        target_node_id=node1.id,
        type="WRITTEN_IN",
        properties={"confidence": 0.99},
        layers={"core"},
    )

    print("Node 1:", node1.model_dump_json(indent=2))
    print("\nNode 2:", node2.model_dump_json(indent=2))
    print("\nEdge:", edge.model_dump_json(indent=2))

    # Example with embedding (assuming numpy array)
    try:
        import numpy as np

        node3 = KnowledgeNode(
            labels={"TextChunk"},
            properties={"text": "This is a sample text."},
            embedding=np.array([0.1, 0.2, 0.3]),
            layers={"ingested_docs"},
        )
        print(
            "\nNode 3 (with embedding):", node3.model_dump(exclude={"embedding"})
        )  # Exclude embedding for cleaner print
        print("Embedding Type:", type(node3.embedding))
    except ImportError:
        print("\nNumpy not installed, skipping embedding example.")
